package com.atlas.exception;

public enum ErrorCode {
    VALIDATION_ERROR,
    RESOURCE_NOT_FOUND,
    UNAUTHORIZED,
    FORBIDDEN,
    CONFLICT,
    EMAIL_ALREADY_REGISTERED,
    INVALID_CREDENTIALS,
    SLUG_TAKEN,
    PROJECT_KEY_TAKEN,
    SEAT_LIMIT_EXCEEDED,
    INVITATION_EXPIRED,
    ALREADY_MEMBER,
    INTERNAL_ERROR
}
