package com.atlas.exception;

public enum ErrorCode {
    VALIDATION_ERROR,
    RESOURCE_NOT_FOUND,
    UNAUTHORIZED,
    FORBIDDEN,
    CONFLICT,
    EMAIL_ALREADY_REGISTERED,
    INVALID_CREDENTIALS,
    SLUG_TAKEN,
    INTERNAL_ERROR
}
